site_name: My Personal Site 
site_url: https://tomfieber.github.io
site_description: A blog about pentesting, security, and technology.
repo_url: https://github.com/tomfieber/tomfieber.github.io
repo_name: tomfieber/tomfieber.github.io
copyright: Copyright © 2025 Tom Fieber

# Theme settings
theme:
  name: material
  custom_dir: overrides
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: blue-grey
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue-grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue-grey
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - search.suggestions
    - search.highlight
    - navigation.footer
    - content.code.copy
    - content.code.annotate
    - content.code.tabs

# Extras
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
  - javascripts/extra.js

extra:
  analytics:
    provider: google
    property: G-HH4Y2D319L
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/tomfieber
    - icon: fontawesome/brands/github
      link: https://github.com/tomfieber
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/thomasfieber
    - icon: fontawesome/brands/discord
      link: https://discord.gg/XvAFFw6A
      

# Plugins
plugins:
  - search
  - blog:
      authors_file: "{blog}/.authors.yml"
      blog_toc: true
  - meta
  - social
  # - git-committers:
  #     repository: tomfieber/tomfieber.github.io
  #     branch: main
  - offline
  - tags
  - glightbox

# Markdown extensions
# markdown_extensions:
#   - pymdownx.highlight:
#       anchor_linenums: true
#       line_spans: __span
#       pygments_lang_class: true
#   - pymdownx.inlinehilite
#   - pymdownx.snippets
#   - pymdownx.superfences
#   - pymdownx.tabbed:
#       slugify: !!python/object/apply:pymdownx.slugs.slugify
#         kwds:
#           case: lower
#       alternate_style: true
#   - pymdownx.tasklist:
#       clickable_checkbox: true
#       custom_checkbox: true
#   - attr_list
#   - pymdownx.emoji:
#       emoji_index: !!python/name:material.extensions.emoji.twemoji
#       emoji_generator: !!python/name:material.extensions.emoji.to_svg
#   - tables
#   - pymdownx.critic
#   - pymdownx.caret
#   - pymdownx.keys
#   - pymdownx.mark
#   - pymdownx.
#   - admonition
#   - pymdownx.details

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tasklist:
      clickable_checkbox: true
      custom_checkbox: true