authors:
  tomfieber:
    name: Tom Fieber        # Author name
    description: Dad, husband, okay pentester # Author description
    avatar: https://avatars.githubusercontent.com/u/108031577?v=4         # Author avatar
    url: https://tomfieber.github.io            # Author website URL